# Build dependabot PR

trigger:
- dependabot/*

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.14.2'
  displayName: 'Install Node.js'

- script: npm install
  displayName: 'npm install'

- script: npm test
  displayName: 'npm test'
